### ISSUE TITLE
No devices or entities

### ISSUE THREAD

**Issue by mikedhanson** [arturzx/homeassistant-iqua-softener#13]
Walking through the setup process I was able to install the integration but when adding the device I get the following with no entities or devices. 

Logs: 

```
2024-01-29 20:06:32.131 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up iqua_softener platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/iqua_softener/sensor.py", line 155, in _async_update_data
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iqua_softener/sensor.py", line 156, in <lambda>
    lambda: self._iqua_softener.get_data()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/iqua_softener/iqua.py", line 89, in get_data
    raise IquaSoftenerException(
iqua_softener.iqua.IquaSoftenerException: Invalid status (401) for data request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iqua_softener/sensor.py", line 159, in _async_update_data
    raise UpdateFailed(f"Get data failed: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Get data failed: Invalid status (401) for data request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/iqua_softener/sensor.py", line 59, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 272, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Get data failed: Invalid status (401) for data request
2024-01-29 20:06:58.089 ERROR (stream_worker) 

```

**Comment by mikedhanson** [comment]
UPDATE: I didnt know you needed to use the DNS value. I was using the system serial number
