### ISSUE TITLE
Error 429 in initial setup

### ISSUE THREAD

**Issue by jgosnell56** [arturzx/homeassistant-iqua-softener#7]
I am setting up for the first time and am receiving this error in the HA Logs
`2023-03-10 20:41:37.834 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.iqua_softener
2023-03-10 20:41:38.375 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up iqua_softener platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/iqua_softener/sensor.py", line 155, in _async_update_data
    return await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/iqua_softener/sensor.py", line 156, in <lambda>
    lambda: self._iqua_softener.get_data()
  File "/usr/local/lib/python3.10/site-packages/iqua_softener/iqua.py", line 85, in get_data
    raise IquaSoftenerException(
iqua_softener.iqua.IquaSoftenerException: Invalid status (429) for data request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/iqua_softener/sensor.py", line 159, in _async_update_data
    raise UpdateFailed(f"Get data failed: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Get data failed: Invalid status (429) for data request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/iqua_softener/sensor.py", line 59, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 211, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Get data failed: Invalid status (429) for data request`

I have doubled check my credentials and that I am using the DSN#, and that it is correct.

**Comment by arturzx** [comment]
This is because your account automatically is locked because making many API calls. In last weeks company changed this service and blocking users depends on how many they calls API. One user reported that support say him that limit is 1000 requests/24h, I've changed interval to 5 minutes to meet this limit but some users still receiving this error. For me 5 minutes interval working.

You may read more on this links:
https://github.com/arturzx/homeassistant-iqua-softener/issues/6
https://community.home-assistant.io/t/rheem-water-softener/326937

**Comment by jgosnell56** [comment]
I saw that thread but didn't think this was the issue since the integration never fully setup up.  None of the devices or entities were ever created.
